"""Add proposal and proposal_document tables

Revision ID: 805af02890e1
Revises: 95a7607a8fc5
Create Date: 2025-06-03 13:51:52.435957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805af02890e1'
down_revision: Union[str, None] = '95a7607a8fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
